/* Axel settings, generated by configure */
#define _REENTRANT
#define _THREAD_SAFE
#define ETCDIR "/usr/local/etc"
#define LOCALE "/usr/local/share/locale"
#define ARCH "WIN32"
#define NUM_CONN 10
#define DEBUG
